### ISSUE TITLE
JTileDownloader gets Forbidden from Mapnik

### ISSUE THREAD

**Issue by ezizrehimov** [Zverik/JTileDownloader#2]
I  need to download some tiles to use them offline in a webpage using JTileDownloader, version 0-6-1.

When I use Mapnik as the source, it get a 'Forbidden' message. what may be happening?

**Comment by Zverik** [comment]
You would need to close the repository, change the user agent [here](https://github.com/Zverik/JTileDownloader/blob/main/src/org/openstreetmap/fma/jtiledownloader/Constants.java#L26) to any random string, do `ant package`, and then run the resulting jar file. Alas, the tile server is blocking JTD by the user agent string.
